### ISSUE TITLE
Add_dependency for eigen_quadprog in CMakeLists not working with current release of jrl-umi3218/eigen-quadprog 

### ISSUE THREAD

**Issue by NoelieRamuzat** [stack-of-tasks/jrl-walkgen#20]
Hi ! 

The latest modifications in the CMakeLists which use` ADD_PROJECT_DEPENDENCY(eigen-quadprog REQUIRED)` and `TARGET_LINK_LIBRARIES(${PROJECT_NAME} eigen-quadprog::eigen-quadprog)` instead of `ADD_REQUIRED_DEPENDENCY("eigen-quadprog >= 1.0.0")` and `PKG_CONFIG_USE_DEPENDENCY(${PROJECT_NAME} eigen-quadprog)` is not working with the current release of [jrl-umi3218/eigen-quadprog](https://github.com/jrl-umi3218/eigen-quadprog/tree/master).

It should be working after the next release of `eigen-quadprog` (because the relevant commits have not been yet released).

**Comment by nim65s** [comment]
I totally missed this issue, sorry @NoelieRamuzat.
It also independently hit @Hugo-L3174: https://github.com/stack-of-tasks/jrl-walkgen/pull/18#discussion_r464425158.

I updated eigen-quadprog on robotpkg, so I'll have to release jrl-walkgen now to fix this issue.

**Comment by nim65s** [comment]
done :)
